# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- job:
    name: libvirt-tls-sidecar-go-test
    parent: golang-go-test
    vars:
      go_version: "1.22.6"
      go_package_dir: "..."

- job:
    name: libvirt-tls-sidecar-build-container-image
    parent: ci-build-container-image
    vars: &container_image_vars
      promote_container_image_job: libvirt-tls-sidecar-upload-container-image
      container_images:
        - context: .
          registry: registry.atmosphere.dev
          repository: registry.atmosphere.dev/library/libvirt-tls-sidecar
          arch:
            - linux/amd64
            - linux/arm64
          tags:
            - "{{ zuul.commit_id }}"
            - "{{ zuul.tag is defined | ternary(zuul.tag, 'main') }}"

- job:
    name: libvirt-tls-sidecar-upload-container-image
    parent: ci-upload-container-image
    vars: *container_image_vars

- job:
    name: libvirt-tls-sidecar-promote-container-image
    parent: ci-promote-container-image
    vars: *container_image_vars

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - libvirt-tls-sidecar-go-test
        - libvirt-tls-sidecar-build-container-image
    gate:
      jobs:
        - libvirt-tls-sidecar-go-test
        - libvirt-tls-sidecar-upload-container-image
    promote:
      jobs:
        - libvirt-tls-sidecar-promote-container-image
